### ISSUE TITLE
Feature Request:: RabbitMQ Container

### ISSUE THREAD

**Issue by NathanDayMF** [clean-docker/Magento2#83]
## Background
with the RabbitMQ module being downgraded from CE to OS would it be possible to add a RabbitMQ Container to this setup. I don't know whether this would be a separate container or something installed on the image if it is possible to do this just by modifying the docker-compose config then if someone could point me in the right direction (bit of a docker noob)

## UAC
- [ ] RabbitMQ is added to the Setup
- [ ] Magento 2.3.0 Can connect to RabbitMQ

**Comment by NathanDayMF** [comment]
for anyone interested in this, think I've figured something out, want to do some more testing before pushing a PR

`docker-compose.yml`
```YAML
rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
    networks:
      - mgento2-docker-network
```

`rabbitmq-isolated.conf`
````CONF
[
 {rabbit,
  [
   %% The default "guest" user is only permitted to access the server
   %% via a loopback interface (e.g. localhost).
   %% {loopback_users, [<<"guest">>]},
   %%
   %% Uncomment the following line if you want to allow access to the
   %% guest user from anywhere on the network.
   {loopback_users, []},
   {default_vhost,       "/"},
   {default_user,        "magento"},
   {default_pass,        "magento"},
   {default_permissions, [".*", ".*", ".*"]}
  ]}
]
```

`app/etc/env.php`
```PHP
'queue' => [
    'amqp' => [
        'host' => 'rabbitmq',
        'port' => '5672',
        'user' => 'magento',
        'password' => 'magento',
        'virtualhost' => '/',
        'ssl' => false
    ]
]
```
